---
abstract: 'Scripts to cross-check Build.PL/Makefile.PL with Module::CoreList, etc'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Metadata-CoreList
provides:
  Module::Metadata::CoreList:
    file: lib/Module/Metadata/CoreList.pm
    version: 1.07
  Module::Metadata::CoreList::Config:
    file: lib/Module/Metadata/CoreList/Config.pm
    version: 1.07
requires:
  Capture::Tiny: 0
  Config: 0
  Config::Tiny: 0
  Date::Simple: 0
  File::Copy: 0
  File::HomeDir: 0.99
  File::Spec: 0
  Getopt::Long: 0
  Hash::FieldHash: 0
  Module::CoreList: 2.61
  Path::Class: 0
  Pod::Usage: 0
  Text::Xslate: 0
  strict: 0
  warnings: 0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.07
